spring.datasource.url=jdbc:postgresql://localhost:5432/db_autoflex
spring.datasource.username=your_username_here
spring.datasource.password=your_password_here
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true